name: ios-tests
on:
    push:
        branches:
            - main
        paths:
            - 'apps/ios/**'
            - '.github/workflows/ios-tests.yml'
    pull_request:
        branches:
            - main
        paths:
            - 'apps/ios/**'
jobs:
    unit-tests:
        runs-on: macos-14
        steps:
            - uses: actions/checkout@v4
            - name: setup
              run: |
                sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
                gem install xcpretty
            - name: Build
              run: >
                xcodebuild build-for-testing -workspace apps/ios/GuideDogs.xcworkspace
                -scheme Soundscape -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'
                CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
                | tee xcodebuild.log | xcpretty && exit ${PIPESTATUS[0]}
            - name: uploadlog
              uses: actions/upload-artifact@v4
              with:
                name: xcodebuild-log
                path: xcodebuild.log
            - name: Test
              run: >
                xcodebuild test-without-building -workspace apps/ios/GuideDogs.xcworkspace
                -scheme Soundscape -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'
